#######################################################
#  _   _      _ _                         __ _        #
# | | | | ___| (_)_  __   ___ ___  _ __  / _(_) __ _  #
# | |_| |/ _ \ | \ \/ /  / __/ _ \| '_ \| |_| |/ _` | #
# |  _  |  __/ | |>  <  | (_| (_) | | | |  _| | (_| | #
# |_| |_|\___|_|_/_/\_\  \___\___/|_| |_|_| |_|\__, | #
#                     By TWB0109                |___/ #
#                                                     #
#######################################################

theme = "gruvbox"

[editor]
line-number = "relative"
shell       = ["powershell", "/C"]
# shell       = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space   = "all"
tab     = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

#[keys.normal]
#"C-backspace" = ["normal_mode", "bc"]
[keys.insert]
"C-backspace" = ["normal_mode", "move_prev_word_start", "change_selection"]
